export const LOGOUT = "CLEAR_USER_DATA";
export const USER_LOGIN_COMPLETED = "USER_LOGIN_COMPLETED";
export const USER_UPDATE_COMPLETED = "USER_UPDATE_COMPLETED";
export const RELATIONSHIP_UPDATE_COMPLETED = "RELATIONSHIP_UPDATE_COMPLETED";